language: ruby
services:
  - postgresql
before_script:
  - psql -c 'create database exportgifsound_test;' -U postgres
  - bundle exec rails db:schema:load
script:
  - bundle exec rake
  - bin/provision_server
