---
- hosts: all
  user: root
  vars:
    database_user: "{{lookup('env', 'DATABASE_USER')}}"
    database_password: "{{lookup('env', 'DATABASE_PASSWORD')}}"
    database_name: "imploder_production"
    application_path: /var/www/app
    env_vars:
      secret_key_base: "{{lookup('env', 'SECRET_KEY_BASE')}}"
      database_url: 'postgres://{{database_user}}:{{database_password}}@localhost:5432/{{database_name}}'
      sidekiq_username: "{{lookup('env', 'SIDEKIQ_USERNAME')}}"
      sidekiq_password: "{{lookup('env', 'SIDEKIQ_PASSWORD')}}"
      aws_access_key_id: "{{lookup('env', 'AWS_ACCESS_KEY_ID')}}"
      aws_secret_access_key: "{{lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"
      s3_bucket: "{{lookup('env', 'S3_BUCKET')}}"

  tasks:
    - name: add support for https in apt
      apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
      with_items:
      - apt-transport-https
      - ca-certificates

    - name: add key for passenger repos
      apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x561F9B9CAC40B2F7 id=AC40B2F7 state=present

    - name: add the passenger repo
      apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main'

    - name: force an apt update
      apt: update_cache=yes

    - name: install packages
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - software-properties-common
        - build-essential
        - imagemagick
        - redis-server
        - ffmpeg
        - postgresql
        - postgresql-contrib
        - python-psycopg2
        - nginx-extras
        - passenger
        - libffi-dev
        - libpq-dev
        - git-core
        - curl
        - zlib1g-dev
        - build-essential
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libsqlite3-dev
        - sqlite3
        - libxml2-dev
        - libxslt1-dev
        - libcurl4-openssl-dev
        - python-software-properties
        - libffi-dev

    - name: start redis
      systemd:
        name: redis-server
        state: started

    - name: start postgres
      systemd:
        name: postgresql
        state: started

    - name: configure postgres db
      become: true
      become_user: postgres
      postgresql_db:
        name: '{{database_name}}'

    - name: configure postgres user
      become: true
      become_user: postgres
      postgresql_user:
        db: '{{database_name}}'
        name: '{{database_user}}'
        password: '{{database_password}}'
        priv: ALL

    - name: tell nginx to enable the passenger module
      lineinfile:
        dest: /etc/nginx/nginx.conf
        regexp: 'passenger.conf'
        line: 'include /etc/nginx/passenger.conf;'

    - name: enable and configure the nginx site
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
            listen 80;
            passenger_enabled on;
            root {{application_path}}/current/public;
            passenger_user deploy;
            passenger_group deploy;
            passenger_ruby /home/deploy/.rbenv/shims/ruby;
          	passenger_env_var PATH ~/.rbenv/bin:/usr/bin:/bin;            
          }

    - name: wrap sidekiq in an systemd service
      copy:
        dest: /lib/systemd/system/sidekiq.service
        content: |
          [Unit]
          Description=sidekiq
          After=syslog.target network.target redis-server.service

          [Service]
          Type=simple
          WorkingDirectory={{application_path}}
          ExecStart=/usr/local/bin/bundle exec sidekiq -e production
          User=deploy
          Group=deploy
          UMask=0002
          Environment=DATABASE_URL={{env_vars.database_url}}

          RestartSec=1
          Restart=on-failure

          StandardOutput=syslog
          StandardError=syslog

          SyslogIdentifier=sidekiq

          [Install]
          WantedBy=multi-user.target

    - name: start the sidekiq service
      systemd:
        name: sidekiq
        enabled: yes
        state: started
        daemon_reload: yes

    - name: make nginx reload its configuration
      systemd:
        name: nginx
        state: reloaded

    - name: create the deploy user
      user:
        name: deploy
        shell: /bin/bash

    - name: authorize the deploy key
      authorized_key:
        user: deploy
        key: "{{ lookup('file', './config/imploder-staging.key.pub') }}"

    - name: install rbenv for the deploy user
      become: true
      become_user: deploy
      git:
        repo: git://github.com/sstephenson/rbenv.git
        dest: ~/.rbenv
        clone: yes

    - name: make sure the bash profile exists
      become: true
      become_user: deploy
      file:
        path: ~/.bash_profile
        state: touch

    - name: add the rbenv shim at the end of shell startup
      become: true
      become_user: deploy
      lineinfile:
        dest: ~/.bash_profile
        line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

    - name: initialize rbenv on profile load
      become: true
      become_user: deploy
      lineinfile:
        dest: ~/.bash_profile
        line: 'eval "$(rbenv init -)"'

    - name: set application environment variables
      become: true
      become_user: deploy
      lineinfile:
        dest: ~/.bash_profile
        line: "export {{ item.key|upper }}={{ item.value }}"
      with_dict: "{{env_vars}}"

    - name: install ruby-build
      become: true
      become_user: deploy
      git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: ~/.rbenv/plugins/ruby-build
        clone: yes

    - name: install rbenv-default-gems
      become: true
      become_user: deploy
      git:
        repo: https://github.com/rbenv/rbenv-default-gems.git
        dest: ~/.rbenv/plugins/rbenv-default-gems
        clone: yes

    - name: install bundler for each ruby version
      become: true
      become_user: deploy
      lineinfile:
        dest: ~/.rbenv/default-gems
        line: 'bundler'
        create: yes

    - name: set the application data directory
      file:
        path: '{{application_path}}'
        state: directory
        owner: deploy
        group: deploy
        mode: 0755

    - name: install ruby
      become: true
      become_user: deploy
      shell: /home/deploy/.rbenv/bin/rbenv install --skip-existing 2.3.3
      args:
        executable: /bin/bash
