default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: imploder_development

test:
  <<: *default
  database: imploder_test

production:
  <<: *default
  database: imploder_production
